name: Main

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-workflow-queue@v1 #If the same workflow is already running from a previous commit, wait for it to finish
    - uses: actions/checkout@v4
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --no-verification

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@<action version> # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
